DROP DATABASE DESAFIO;

CREATE DATABASE DESAFIO;

USE DESAFIO;

CREATE TABLE USERS (
    ACCOUNTID INT IDENTITY(1,1) PRIMARY KEY,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    PASSWD VARCHAR(50) NOT NULL,
    SALT VARCHAR(15) NOT NULL,
    PHONE VARCHAR(11) NOT NULL,
    CPF VARCHAR(11) NOT NULL,							
    ACCOUNTTYPE VARCHAR(15) DEFAULT 'COMUM',
    BALANCE INT DEFAULT 0
);

INSERT INTO USERS ( EMAIL, PASSWD, PHONE, CPF, BALANCE)VALUES ('ADDAASDA@DASDSA', '132SDAD', 1312312, 3131222, 0);
SELECT * FROM USERS;
SELECT PASSWD, SALT FROM USERS WHERE EMAIL = 'Eu@eu';
SELECT * FROM USERS WHERE EMAIL = 'A@a';
UPDATE USERS SET BALANCE = BALANCE - 10 WHERE ACCOUNTID = 1;
UPDATE USERS SET ACCOUNTTYPE = 'ADMIN' WHERE ACCOUNTID = 1;
DELETE FROM USERS WHERE ACCOUNTID = 3;
SELECT @@SERVERNAME