DROP DATABASE DESAFIO;

CREATE DATABASE DESAFIO;

USE DESAFIO;

CREATE TABLE USERS (
    ACCOUNTID INT IDENTITY(1,1) PRIMARY KEY,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    PASSWD VARCHAR(50) NOT NULL,
    SALT VARCHAR(15) NOT NULL,
    PHONE VARCHAR(11) NOT NULL,
    CPF VARCHAR(11) NOT NULL,							
    ACCOUNTTYPE VARCHAR(15) DEFAULT 'COMUM',
    BALANCE INT DEFAULT 0
);

CREATE TABLE MESSAGES(
    MESSAGEID INT IDENTITY(1,1) PRIMARY KEY,
    MESSAGECONTENT MEDIUMTEXT NOT NULL,
    RECEIVER SMALLTEXT NOT NULL,
    SENDER INT NOT NULL,
    STATUS VARCHAR(200) NOT NULL,
    FOREIGN KEY SENDER REFERENCES USERS(ACCOUNTID) 
);

INSERT INTO USERS ( EMAIL, PASSWD, PHONE, CPF, BALANCE)VALUES ('ADDAASDA@DASDSA', '132SDAD', 1312312, 3131222, 0);
SELECT * FROM USERS;
SELECT PASSWD, SALT FROM USERS WHERE EMAIL = 'Gabriel@eu';
SELECT BALANCE FROM USERS WHERE ACCOUNTID = 12;
UPDATE USERS SET BALANCE= 100 WHERE ACCOUNTID = 12
DELETE FROM USERS WHERE ACCOUNTID = 3;
SELECT * FROM USERS WHERE EMAIL = 'Gabriel@rodrigues44'
SELECT @@SERVERNAME