CREATE DATABASE DESAFIO;


CREATE TABLE USERS (
    ACCOUNTID INT IDENTITY(1,1) PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWD VARCHAR(50) NOT NULL,
    PHONE VARCHAR(11) NOT NULL,
    CPF VARCHAR(11) NOT NULL,							
    ACCOUNTTYPE INT DEFAULT 1,
    BALANCE INT NOT NULL
);

INSERT INTO USERS ( EMAIL, PASSWD, PHONE, CPF, BALANCE)VALUES ('ADDAASDA@DASDSA', '132SDAD', 1312312, 3131222, 0);
SELECT * FROM USERS;