CREATE DATABASE DESAFIO;

USE DESAFIO;

CREATE TABLE USERS(
    EMAIL VARCHAR(50) NOT NULL,
    PASSWD PASSWORD NOT NULL,
    PHONE VARCHAR(11) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ACCOUNTID INT IDENTITY(1,1),
    ACCOUNTTYPE INT DEFAULT 1,
    BALANCE INT NOT NULL
)
-- perguntar para o diego sobre os relatorios
--CREATE TABLE RELATORIO(

--)